/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { iAvenger } from "./components/my-list/my-list";
export namespace Components {
    interface MyComponent {
        "bool": boolean;
        "str": string;
        "toggle": () => Promise<void>;
    }
    interface MyInput {
        "disabled": boolean;
        "label": string;
        "name": string;
        "placeholder": string;
    }
    interface MyList {
        "setAvengersArr": (arr: iAvenger[]) => Promise<void>;
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
export interface MyListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyListElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyListElement extends Components.MyList, HTMLStencilElement {
    }
    var HTMLMyListElement: {
        prototype: HTMLMyListElement;
        new (): HTMLMyListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-input": HTMLMyInputElement;
        "my-list": HTMLMyListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "bool"?: boolean;
        "onMyAvengerEvent"?: (event: MyComponentCustomEvent<string>) => void;
        "str"?: string;
    }
    interface MyInput {
        "disabled"?: boolean;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
    }
    interface MyList {
        "onMyAvengerEvent"?: (event: MyListCustomEvent<iAvenger>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-input": MyInput;
        "my-list": MyList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-list": LocalJSX.MyList & JSXBase.HTMLAttributes<HTMLMyListElement>;
        }
    }
}
